### ISSUE TITLE
[UX] Add dropdown for horizontal mode

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#10]
This is the same issue as https://www.drupal.org/project/navbar/issues/2481207 and it basically attempts to add the functionality provided by the https://www.drupal.org/project/admin_toolbar module for D8 (no D7 version for it):

![admin_toolbar](https://user-images.githubusercontent.com/2423362/55687730-95473280-59b3-11e9-955b-9bea8d41a6a6.gif)

That module counts [120k installations](https://www.drupal.org/project/usage/admin_toolbar); when [D8 has 315k](https://www.drupal.org/project/usage/drupal). So it seems to be a very popular feature.

**Comment by klonos** [comment]
I have created a PR here: #11 

It is based off of the [latest patch](https://www.drupal.org/files/issues/dropdown_for_navbar-2481207-22.patch) available in https://www.drupal.org/project/navbar/issues/2481207. It still needs work:

- See if we can get rid of the excessive usage of `!important`
- Some menus like "User accounts" and "Functionality" do not get a drop-down
- Some 3+ level menus do not get expanded to show sub-menus (like "Structure" -> "Layouts" for example)
- There are some menu items that should not be there. For example "Configuration" -> "Workflow"
- Some menu items are missing. For example there is only a single "Basis settings" menu item under "Appearance"; all other menu items that should be there, are not. Same with "Content", which only has a single "Manage comments" item.
- In Basis, the main navigation menu intercepts the Navbar dropdown, so people cannot use some of the menus. Could be as simple as setting zindex.

Some of the above problems could be related to #8 and/or #9

**Comment by VasasA** [comment]
Thank You the PR!
Please, consider that the Navbar uses the admin/structure/menu/manage/management page's menu structure with 'weights' when create its menu-system.
![kép](https://user-images.githubusercontent.com/8567234/55689683-f6591100-5987-11e9-95ec-2ec16a28a85c.png)

**Comment by VasasA** [comment]
@klonos I analyzed the list of '[needs work:](https://github.com/VasasA/navbar/issues/10#issuecomment-480616664)'
- First remark: I will exam the usage of `!important`. 
- Last remark: I increased z-index to 999 because Basis theme uses 998. :open_mouth:  [Fixed](https://github.com/VasasA/navbar/commit/3b88934bcbfadd2e2e679766c5d1ed66ef03f3cf).
- All of other remark: It isn't problem of Navbar, we souldn't change the code of the module, because the Navbar uses the admin/structure/menu/manage/management page's menu structure when builds its menu-system. Is it true?

**Comment by VasasA** [comment]
@klonos I examined the usage of `!important`.  See this [video](https://vimeo.com/329304654).
If I remove the `!important` from a CSS property, the property will be crossed out. So I think the `!important` is really important.

**Comment by VasasA** [comment]
Possible solutions by @klonos:
- Navbar is using admin_bar_links_menu(admin_bar_tree('management')) for generating the admin menu structure.
- The core (system.module perhaps?) could provide a common function that generates the admin menu structure, and then both Admin_bar and Navbar can use that.

**Comment by VasasA** [comment]
Fixed: I used a modified function: core/includes/menu.inc -> menu_tree_output()
https://github.com/backdrop-contrib/navbar/commit/474df5a61609854502f1e4f20db5dd73131c5db6

**Comment by klonos** [comment]
This works @VasasA 👍 🎉 ...but as also mentioned on Gitter, we should add a comment to the customised function, explaining why this needed to be done that way. Then also add a `@todo`.

If the core function `menu_tree_output()` does not work as expected in this case, we should fix that in core if possible.

**Comment by klonos** [comment]
...for posterity, the line that was modified was 574:

```php
if ($data['link']['access'] && (intval($data['link']['hidden'])<1) && $data['link']['type'] != MENU_VISIBLE_IN_BREADCRUMB) {
```
