### ISSUE TITLE
[UX] Conflict with Admin Bar

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#12]
When the Navbar module is enabled at the same time as with the Admin Bar module provided by core, the Admin Bar menu covers the Navbar. We seem to have a few options here:

- Add a check to see if admin_bar is enabled, then throw a warning to tell people that these modules do not work well together, and that they should disable admin_bar if they want to use Navbar
- Prevent the two modules from being enabled at the same time. This would require core changes though so that this can be supported in .info files: https://www.drupal.org/project/drupal/issues/92233
- Use `admin_bar_suppress()` when Navbar is enabled.
- Use `hook_requirements()` when installing Navbar
- Use a setting (permission?) that allows either admin_bar or navbar to be used by different user roles.
- any other solution???

**Comment by VasasA** [comment]
The module doesn't exam this requirement now. Only there is an [attention](https://github.com/VasasA/navbar#attention) in the README.md like in the original D7 module.
But I try improve it.

**Comment by VasasA** [comment]
I think the `admin_bar_suppress()` is the best solution for the users: https://github.com/backdrop-contrib/navbar/commit/0ee6eb7aba778ad12b8cb7328b55738cbddf58b3
