### ISSUE TITLE
"Back to site" not working as expected

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#14]
## Steps to reproduce

- From the front page, navigate to the "About" page (`/about`)
- Using the Navbar menu, navigate to any admin page (`/admin/modules` for example)

## Actual behavior

The "Back to site" menu links to the home page 👎 

## Expected behavior

The "Back to site" menu should link to the frontend page the user came from (`/about`).

**Comment by VasasA** [comment]
Fixed. https://github.com/backdrop-contrib/navbar/commit/a51666893685c8a90762ac242d3f9d749addb5d0
I had to move content of hook_page_alter() into hook_preprocess_page().
Related: [ New Layout module](https://api.backdropcms.org/change-records/new-layout-module-implements-drag-drop-model-building-layouts)
