### ISSUE TITLE
Remove ducktape.events.js

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#15]
Backdrop currently ships with jQuery 1.12.4 (Backdrop 1.0.0 shipped with 1.11.1), and we always keep it up to date. Navbar includes `js/jquery/ducktape.events.js`, which states the following:

```
 * Navbar 1.x depends on jQuery >=1.7 (it uses jQuery.fn.on & jQuery.fn.off).
 * We re-implement these in terms of jQuery.fn.bind, jQuery.fn.delegate,
 * jQuery.fn.unbind, and jQuery.fn.undelegate.
 * This allows us to use Backbone 1.x with Backdrop's jQuery 1.4.
```

This might have been a requirement with Drupal 7, which ships with jQuery 1.4,  but we shouldn't need it in Backdrop. Lets remove it.

**Comment by VasasA** [comment]
Thank You! Removed: https://github.com/backdrop-contrib/navbar/commit/4c10325b767fbf16233e43cc0ca6034a7880e2e4
