### ISSUE TITLE
Style the searchbar more like Navbar

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#16]
I am testing the [`searchbar` branch](https://github.com/backdrop-contrib/navbar/tree/searchbar). This is great work once again @VasasA 👍 

The searchbar currently is styled same as the core Admin Bar. We should style it to look more like the rest of the Navbar.

One thing missing is the functionality that automatically opens and highlights the respective menu item, when you hover your mouse over the searchbar results. This will only be possible in the horizontal mode though I believe.

**Comment by VasasA** [comment]
Fixed: highlights the respective menu item: https://github.com/backdrop-contrib/navbar/commit/63bb3a4b15b2425145ee44bf1d399a91f57b7719
I modified the style same as the Navbar: font-family, font-size, padding-color etc.: https://github.com/backdrop-contrib/navbar/commit/740ed45c17dcea7bcd06c6d5380040ab9bffc2c9
Is it nice?

**Comment by klonos** [comment]
I have taken a look at the code. Occurrences of `$adminBar` should be changed to `$navBar`, and `admin-bar-*` classes should be changed to `navbar-*` instead.

The searchbar does not work in vertical mode, but that can be solved in another, follow-up issue.

When I was referring to the style, I was talking more about colors. The searchbar results are black background with white text, while the Navbar menus are white background with dark text. Also, hover over searchbar results adds blue background, while the rest of the Navbar has light gray color.

Other than those comments, this works great.

**Comment by VasasA** [comment]
Thank You for the details.
This is suitable for testing: https://github.com/backdrop-contrib/navbar/tree/searchbar

**Comment by VasasA** [comment]
I have merged the searchbar branch included "Configuration" page.
This is suitable for testing in the default branch: https://github.com/backdrop-contrib/navbar
