### ISSUE TITLE
[UX] Vertical mode: Clicking on the menu arrow should expand the menu

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#18]
As it is now, this does not work as expected (and does not match how the D8 menu works either). So:

- Switch Navbar to vertical mode
- Click on the arrow next to a top-level item

## Current behavior

The page of that menu item is loaded, and the menu is now expanded

## Expected behavior

The menu item should expand, but the page should not be loaded. If the user wants to visit that menu page, they should click on the menu link itself (not on the arrow).

**Comment by VasasA** [comment]
Thank You!
Problem with z-index: Menu link's z-index is higher then arrow's. Cause: https://github.com/backdrop-contrib/navbar/commit/3b88934bcbfadd2e2e679766c5d1ed66ef03f3cf
Fixed: https://github.com/backdrop-contrib/navbar/commit/5d6401fb699aa4e5b8986d7c852efc7ed180c454
Should I create a new relesase? : 1.x-1.7.2

**Comment by klonos** [comment]
This works as expected now 👍

>Should I create a new relesase? : 1.x-1.7.2

Yeah, I think so.
