### ISSUE TITLE
Use the same arrow colors in vertical and horizontal mode

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#20]
Horizontal mode has small, gray arrows, while vertical mode uses larger, blue arrows:

<img width="439" alt="Screen Shot 2019-04-16 at 2 43 48 am" src="https://user-images.githubusercontent.com/2423362/56150521-70297400-5ff2-11e9-88bd-3b2e68f47dbc.png">

<img width="330" alt="Screen Shot 2019-04-16 at 2 52 35 am" src="https://user-images.githubusercontent.com/2423362/56150692-c5658580-5ff2-11e9-892d-a52465d3ba0e.png">

I think that we should be using the same arrows for horizontal/vertical mode.

In fact, these arrows are to be changed in the new Claro admin theme that's being developed for D8 core (see https://www.drupal.org/project/ideas/issues/3017785#comment-12948735):

![image](https://user-images.githubusercontent.com/2423362/56150457-525c0f00-5ff2-11e9-9b97-d1a341a33a43.png)

I think that these look more modern. We should use `#0074bd` for collapsed/inactive, and `#666666` for expanded/active (not the same colors as the Claro theme, because these will not match the Seven admin theme in Backdrop core). In vertical mode, the expanded arrows should be facing right instead of up.

**Comment by VasasA** [comment]
@klonos Thank You for the detailed description. Fixed.
Please, check the new arrow icons in vertical and horizontal orientation mode.

**Comment by klonos** [comment]
This works beautifully @VasasA 👍 ...a few things to consider:

- The arrows in horizontal mode seem to be blue in https://www.drupal.org/project/admin_toolbar :

    <img width="957" alt="Screen Shot 2019-04-18 at 5 55 20 am" src="https://user-images.githubusercontent.com/2423362/56317419-0e0e7180-61a0-11e9-9c6c-8b997fb4911a.png">

- You can consider providing a "dark" theme for it: #21

**Comment by VasasA** [comment]
Thank You, fixed: https://github.com/backdrop-contrib/navbar/commit/e9eb146fcfa1b4bbb3931507999cddd2ae3992b4
