### ISSUE TITLE
Consider providing a "dark" theme

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#21]
Here's a module that does this: https://www.drupal.org/project/adminimal_admin_toolbar

<img width="958" alt="Screen Shot 2019-04-18 at 5 37 45 am" src="https://user-images.githubusercontent.com/2423362/56317515-4b72ff00-61a0-11e9-930b-aace3fa0fedb.png">

**Comment by VasasA** [comment]
Thank You for the idea. I included the dark theme into the module.
What should be the default theme? Light or dark?
Screenshots: https://github.com/backdrop-contrib/navbar/tree/1.x-1.x/images

**Comment by VasasA** [comment]
Published: https://github.com/backdrop-contrib/navbar/releases/tag/1.x-1.7.4
