### ISSUE TITLE
Certain menu items missing, and some not sorted properly

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#22]
Examples of missing items:

- Content -> Add content
- Structure -> Content types: [all content types and their sub-menus]
- Structure -> Layouts: [all layouts and their sub-menus]
- Structure -> Menus -> [Menu name]: [all menu actions]
- Structure -> Taxonomy: [all vocabularies and their sub-menus]
- Structure -> Views: [all views and their sub-menus]

Not sorted properly:

- Configuration: menu items not sorted properly

**Comment by VasasA** [comment]
Related: https://github.com/backdrop-contrib/navbar/issues/17

**Comment by VasasA** [comment]
Fixed. This was a hard work. :sweat_smile:  https://github.com/backdrop-contrib/navbar/commit/df93c35854fd53c7fe8c91267a79c0d7039c4bcc

**Comment by klonos** [comment]
Thank you for your hard work @VasasA 🙏
