### ISSUE TITLE
Provide a notification badge when errors are found.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#23]
This is a feature we have added in core in https://github.com/backdrop/backdrop-issues/issues/639

<img width="956" alt="Screen Shot 2019-04-18 at 6 26 16 am" src="https://user-images.githubusercontent.com/2423362/56318885-8460a300-61a3-11e9-83e6-5bfaf2cae7fc.png">

We need to show this badge in both horizontal and vertical mode. Here's how it looks in the Admin Bar on mobile mode:

<img width="471" alt="Screen Shot 2019-04-18 at 6 32 07 am" src="https://user-images.githubusercontent.com/2423362/56318955-bb36b900-61a3-11e9-990b-8668fcd328f4.png">

**Comment by VasasA** [comment]
It is useful. Thank You!
Inserted: https://github.com/backdrop-contrib/navbar/commit/58f2f48469c5c8e5116eea738c6d1f7287b18d83
