### ISSUE TITLE
Dark theme: submenu arrows not visible for active menu item.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#33]
<img width="376" alt="Screen Shot 2019-05-22 at 6 06 55 am" src="https://user-images.githubusercontent.com/2423362/58127266-5239d980-7c58-11e9-88a3-348a82df4669.png">

...when you hover over the active menu item, the arrow is shown:

<img width="470" alt="Screen Shot 2019-05-22 at 6 07 03 am" src="https://user-images.githubusercontent.com/2423362/58127267-52d27000-7c58-11e9-924a-0e9d8e5b418f.png">

**Comment by VasasA** [comment]
Thank You! This problem appears in RTL view too.
Fixed. https://github.com/backdrop-contrib/navbar/commit/24ecdaa9a90166cf8718d2df5a38a8eaf21e9ba0
