### ISSUE TITLE
Dark theme: Gray icons not ideal for active items

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#34]
The gray color looks OK for in active menu items (black background), but not so great for active items (blue background):

<img width="376" alt="Screen Shot 2019-05-22 at 6 06 55 am" src="https://user-images.githubusercontent.com/2423362/58127437-bd83ab80-7c58-11e9-8292-4691594f3817.png">

Perhaps try to make them white or black?

**Comment by VasasA** [comment]
Thank You! Fixed. https://github.com/backdrop-contrib/navbar/commit/c5bcf5e4f3e9fef94ff2cc2df1df4bf84bb6cf72
