### ISSUE TITLE
Missing menu to clear caches, run cron, run update.php

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#35]
Admin Bar in core provides this:

<img width="336" alt="Screen Shot 2019-05-25 at 11 19 53 am" src="https://user-images.githubusercontent.com/2423362/58362821-0fd5fe00-7edf-11e9-8c20-3fe10326dec3.png">

**Comment by klonos** [comment]
...unfortunately, I don't have any good recommendation as to where to place this in Navbar 🤔

**Comment by VasasA** [comment]
@klonos Under 'Dashboard'?

**Comment by klonos** [comment]
Yeah, why not. It is not ideal, but the first item to the left of the menu is where people are used to finding these actions. We can move them in the future, if we come up with a better idea.

**Comment by VasasA** [comment]
:fireworks:  Improved! :fireworks: 
(in the default branch)
Commits:
https://github.com/backdrop-contrib/navbar/commit/f90dfd55ea5f79a1ef691e62cc772be4df6b4540
https://github.com/backdrop-contrib/navbar/commit/f7726195a049d50dafda71e031292c07a0a094b1
