### ISSUE TITLE
Drupal Navbar module marked unsupported

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/navbar#37]
Today (Jan 26th, 2022) the Drupal Navbar module was marked unsupported.

I have [offered to co-maintain the Navbar module for Drupal](https://www.drupal.org/project/projectownership/issues/3260737) in the hopes that I can help fix and/or test the solution to the unresolved security issue. 

Once There is a solution that the Drupal security team approves of, both projects should have a matching release. I'm hoping I can help coordinate those releases @VasasA

**Comment by VasasA** [comment]
Thank You very much!

**Comment by jenlampton** [comment]
There is a new release of the Navbar module available:
https://www.drupal.org/project/navbar/releases/7.x-1.8

We should either cherry-pick in the commits from the Drupal project, or re apply all the patches to make a matching Backdrop release. Do you have a preference for which way we approach it @VasasA ?

**Comment by VasasA** [comment]
The new version of Navbar contains only [one new commit](https://git.drupalcode.org/project/navbar/-/commit/6ab3d1cb0d58946ba6c36fd77646455880786355). I created a [new branch](https://github.com/backdrop-contrib/navbar/tree/7.x-1.x), it is a copy of the Drupal version with the new commit. So I can "cherry-pick" from this branch to the main branch (1.x-1.x):
```
git checkout 1.x-1.x
git cherry-pick 6ab3d1c
git push origin 1.x-1.x
```
Is it a correct approach?

**Comment by jenlampton** [comment]
Yep, that sounds great!

**Comment by VasasA** [comment]
1.x-1.8.0 is published. 🎆

**Comment by jenlampton** [comment]
Beautiful, thank you!
