### ISSUE TITLE
"This Page" is lost with NavBar module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/navbar#38]
I like the navbar module, but I also really like the relatively new "This Page" feature in the admin menu which seems to be lost when enabling the navbar module.

![image](https://github.com/backdrop-contrib/navbar/assets/3144571/8f5ff555-1e6f-4043-98aa-237b21c3cce2)

Can we support the "This Page" feature with Navbar.

**Comment by albanycomputers** [comment]
@stpaultim I was just going to post the same... It would be nice to have this feature.

**Comment by stpaultim** [comment]
I may take a stab at creating a PR for this.

**Comment by VasasA** [comment]
@stpaultim @albanycomputers
I couldn't integrate "This page" between the search bar and "User counts". I could create a new item in the main menu. See below. I couldn't put the "Configure" menu under "Layout". So the "Configure" menu is the third. (I think this is the better solution here than a submenu.)
![kép](https://github.com/backdrop-contrib/navbar/assets/8567234/060ebfb5-654f-4732-90e8-421ff221deb9)

![kép](https://github.com/backdrop-contrib/navbar/assets/8567234/cd744803-dcad-4c69-a5db-08cd74070fd0)

**Comment by stpaultim** [comment]
@VasasA - I think your plan is good. 

One suggestion regarding the "Configure" link. Could you edit the link label to "Configure Layout"? 

I think what you have suggested is pretty good, but the positioning of the config item leaves it a little unclear about what the config is for. If it's easy enough to change the link to "Configure Layout", I think it would be helpful. But, I think it's a nice improvement either way.

Thanks for working on this. Clearly, I never got around to looking closer at this.

**Comment by VasasA** [comment]
It's easy to change the link to "Configure Layout". Thank You for the idea and feedback. I will prepare a PR.

**Comment by stpaultim** [comment]
@VasasA I've tested your PR and I think it works good. 

I wonder if you could turn on the option by default or at least for new installs of the module. I think most people adding this module to an existing site with that feature, will expect it to be on by default.

**Comment by VasasA** [comment]
@stpaultim The "This page" tray is turn on by default for new installs of the module. The config/navbar.settings.json file contains the setting for this (all component are turn on):
```
"components": [
        "navbar.shortcut",
        "navbar.user",
        "navbar.this_page",
        "navbar.user_count",
        "navbar.alert",
        "navbar.search"
    ],
```
I have tested, and it works. Maybe you experienced something different?
