### ISSUE TITLE
Testing with 1.28.0-preview

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/navbar#39]
@VasasA 
If you have time it would be good to test with the preview release of 1.28.0, since that version introduces some changes to the admin menu. I don't know if it causes issues here or not.

**Comment by keiserjb** [comment]
![navbar](https://github.com/backdrop-contrib/navbar/assets/41843284/d7892669-c570-4dde-a8e6-899ebd51afcc)

I think there is a problem.  I have not looked at what it could be or how it could be solved.

**Comment by VasasA** [comment]
Thank You!
I fixed the issue of the user counter (not committed yet). I haven't found any other bug. And You?

**Comment by VasasA** [comment]
[Committed.](https://github.com/backdrop-contrib/navbar/commit/5cb92f4fe80006f7c0ae5c91d94fc4ebb20955ad)
