### ISSUE TITLE
Notice: Only variables should be passed by reference in navbar_preprocess_page() (line 229 of navbar.module).

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#6]
I get this on a fresh installation. Perhaps you need to enable all errors to see it (`/admin/config/development/logging`).

**Comment by VasasA** [comment]
Thank You! I fixed: https://github.com/VasasA/navbar/commit/7e407c96cfe65b2236dd567aae3cdcf170591a95
