### ISSUE TITLE
Icons missing from some top-level menu items

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#8]
The following menu items are missing their icons:

- User accounts
- Functionality
- Development (need to install the Devel module to get that)

![Screen Shot 2019-04-08 at 3 46 04 am](https://user-images.githubusercontent.com/2423362/55687507-de49b780-59b0-11e9-9fc2-6ec4438b6990.png)

**Comment by VasasA** [comment]
I have found some icons in navbar\icons\000000 directory:
- User accounts
![kép](https://user-images.githubusercontent.com/8567234/55689523-cf99db00-5985-11e9-8b6a-5c97a7235c3b.png)
- Functionality
![kép](https://user-images.githubusercontent.com/8567234/55689526-dc1e3380-5985-11e9-8662-518748049c1c.png)

But there isn't icon for Development. (like a gear)

**Comment by klonos** [comment]
We are using the `</>` icon for the "Development" menu in admin_bar (we use a gear for "Configuration"):

<img width="934" alt="screen shot 2019-01-09 at 6 30 30 pm" src="https://user-images.githubusercontent.com/397895/50942247-d6738900-143c-11e9-8b80-7142b15ab648.png">

**Comment by VasasA** [comment]
Relevants:
- In the navbar.module the `navbar_menu_navigation_links()` adds the css classes to the menu items.
- These classes are in navbar.icons.css with references of icon files.
- Problem with displaying of menu stucture: In the navbar.module in `navbar_get_menu_tree()` I cannot display the full $tree with dpm(). I must to use these:
```php
foreach ($tree as $k => $v) {dpm($k);}
foreach ($tree['49994 User accounts 19']['link'] as $k => $v) {dpm($k  . '=>' . $v);}
```

**Comment by VasasA** [comment]
Icons and css classes are included. Commits : 
- [Included 'development' icons](https://github.com/VasasA/navbar/commit/5e6cb6a74bd3f17be5144ac5abe7bacf62aea1b6)
- [Gear icon included](https://github.com/VasasA/navbar/commit/cea046f1e798e976881823f6cad1f6e56058779c)
- [Replace icons](https://github.com/VasasA/navbar/commit/6f77af79d7209bff64c557b548a3f99c9e42b3eb)
