### ISSUE TITLE
Content types are being added at the top level of the menu

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/navbar#9]
When you enable the module, the "Post" and "Page" links are added as top-level menu items:

![Screen Shot 2019-04-08 at 3 46 04 am](https://user-images.githubusercontent.com/2423362/55687538-4dbfa700-59b1-11e9-9fd6-f88f3330a9da.png)

If you add another content type, this is also added to the top level of the menu:

![Screen Shot 2019-04-08 at 3 50 18 am](https://user-images.githubusercontent.com/2423362/55687551-82336300-59b1-11e9-82ad-85afca877899.png)

**Comment by VasasA** [comment]
The source of this problem is that the Navbar uses the admin/structure/menu/manage/management page's menu structure when create the menu-system. And there are the content types.
![kép](https://user-images.githubusercontent.com/8567234/55689405-4b932380-5984-11e9-9d43-a87732f90f38.png)

**Comment by VasasA** [comment]
Content type links are ignored. Commit:
[Ignore content types at the top level.](https://github.com/VasasA/navbar/commit/e7fb40fe589bb168151590e9898d2a529620f217)
